apiVersion: apps/v1
kind: Deployment
metadata:
  name: lokaltrivia-deployment
  labels:
    app: lokaltrivia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lokaltrivia
  template:
    metadata:
      labels:
        app: lokaltrivia
    spec:
      containers:
      - name: lokaltrivia
        image:  beatrix1997/lokaltrivia:1.00
        ports:
        - containerPort: 5173 
---
apiVersion: v1
kind: Service
metadata:
  name: lokaltrivia-service
spec:
  type: NodePort
  selector:
    app: lokaltrivia
  ports:
    - protocol: TCP
      port: 5173 
      targetPort: 5173 
      nodePort: 30100